const ExercisePoints = {
  Setup: 0,
  abSideCrunches: 5,
  'Bench Dips': 6,
  'Bent Over Row': 8,
  'Bicep Curls': 4,
  'Bicycle Crunch': 7,
  Burpees: 10,
  'Butt Kick Variation': 3,
  'Dumbbell One-Arm Shoulder Press': 8,
  'Chair Squat': 4,
  'Cobra Pushups': 6,
  'Cross Jacks': 5,
  'Dumbbell FrontRaise': 6,
  'Dumbbell Lunges': 8,
  'Dumbbell Lunge': 8,
  'Dumbbell One Arm Shoulder Press': 7,
  'Dumbbell Romanian Deadlift': 9,
  'Dumbbell Shoulder Press': 7,
  'Hand and Leg Stretch': 3,
  'Hand Planks': 8,
  'Hip Raise': 5,
  'Jumping Jack': 4,
  'Jumping Lunges': 9,
  'Lateral Raises': 6,
  'Leg Lowers': 7,
  Lieups: 4,
  'Lying LegRaise': 6,
  'Mountain Climbers': 8,
  'Pike Pushups': 9,
  Pullups: 10,
  Pushups: 7,
  'Reverse Crunch': 6,
  'Russian Twists': 7,
  'Shoulder Taps': 6,
  'Side Plank': 8,
  Situps: 5,
  Squats: 5,
  'Superman Hold': 9,
  'Tricep Dips': 6,
  VUps: 8,
  'Walking Lunges': 8,
  WallSit: 7,
  'Windshield Wipers': 8,
  yTWLift: 6,
  'dumbbellOne-armShoulderPress': 6,
  'dumbbell One-armShoulderPress': 6,
  'Sit-Up': 5,
  plankUps: 8,
  Thankyou: 0,
};

export default ExercisePoints;
